- hosts: docker_hosts1
  gather_facts: no
  remote_user: root
  tasks:
  - name: update the network
    command: nmcli con mod enp1s0f0 ipv4.addresses 172.21.{{ 7 + 8 * groups['docker_hosts1'].index(inventory_hostname)|int }}.254/12
- hosts: docker_hosts2
  gather_facts: no
  remote_user: root
  tasks:
  - name: update the network
    command: nmcli con mod enp1s0f0 ipv4.addresses 172.23.{{ 47 + 8 * groups['docker_hosts2'].index(inventory_hostname)|int }}.254/12
- hosts: docker_hosts3
  gather_facts: no
  remote_user: root
  tasks:
  - name: update the network
    command: nmcli con mod enp1s0f0 ipv4.addresses 172.29.{{ 19 + 8 * groups['docker_hosts3'].index(inventory_hostname)|int }}.254/12

