- hosts: all
  gather_facts: no
  remote_user: root
  tasks:
    - name: update etc host file with sat ip 
      lineinfile:
        path: /etc/hosts
        regexp: 'f04-h17-b01-5039ms.rdu2.scalelab.redhat.com'
        line: '172.23.39.254 f04-h17-b01-5039ms.rdu2.scalelab.redhat.com'

